/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarDetailHistory;
import model.CarDetails;

/**
 *
 * @author anupritadhamale
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    CarDetailHistory history;
    public SearchJPanel(CarDetailHistory history) {
        initComponents();
        this.history = history;
        
        //populateTable();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchCarDetails = new javax.swing.JTable();
        btnCarAvailability = new javax.swing.JButton();
        btnBrandName = new javax.swing.JButton();
        btnManufacturingYear = new javax.swing.JButton();
        btnSeats = new javax.swing.JButton();
        btnSerialNumber = new javax.swing.JButton();
        btnModelNumber = new javax.swing.JButton();
        btnCityName = new javax.swing.JButton();
        btnExpiredCertificate = new javax.swing.JButton();
        btnManufacturers = new javax.swing.JButton();
        btnCarName = new javax.swing.JButton();

        txtSearchTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtSearchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSearchTitle.setText("Search Car Details ");

        tblSearchCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Availability", "Brand", "Mfg Company", "seats", "SerialNo", "ModelNo", "CityName", "ExpLicCertificate"
            }
        ));
        jScrollPane1.setViewportView(tblSearchCarDetails);

        btnCarAvailability.setText("How many cars are currently available. How many are not.");
        btnCarAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarAvailabilityActionPerformed(evt);
            }
        });

        btnBrandName.setText("List all cars by the brand name");
        btnBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandNameActionPerformed(evt);
            }
        });

        btnManufacturingYear.setText("List all cars that were manufactured in a given year, ‘x’.");
        btnManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturingYearActionPerformed(evt);
            }
        });

        btnSeats.setText("List all cars with a minimum and maximum number of seats");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        btnSerialNumber.setText("Find a car with the given serial number and List the attributes");
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        btnModelNumber.setText("List all cars given the model number");
        btnModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNumberActionPerformed(evt);
            }
        });

        btnCityName.setText("List all cars that are available in a given city.");
        btnCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityNameActionPerformed(evt);
            }
        });

        btnExpiredCertificate.setText("List all cars that have expired maintenance certificate");
        btnExpiredCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredCertificateActionPerformed(evt);
            }
        });

        btnManufacturers.setText("List all the car manufacturers used in this application");
        btnManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturersActionPerformed(evt);
            }
        });

        btnCarName.setText("Find the first car available ");
        btnCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarName)
                    .addComponent(btnCarAvailability)
                    .addComponent(btnBrandName)
                    .addComponent(btnManufacturingYear)
                    .addComponent(btnSeats)
                    .addComponent(btnSerialNumber)
                    .addComponent(btnModelNumber)
                    .addComponent(btnCityName)
                    .addComponent(btnExpiredCertificate)
                    .addComponent(btnManufacturers))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarAvailability)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrandName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacturingYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSerialNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModelNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCityName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpiredCertificate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacturers)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarAvailabilityActionPerformed
        // TODO add your handling code here:
         //DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        //String CarAvailability1 = null;
       // String carAvailability = JOptionPane.showInputDialog("Is the car available ", CarAvailability1);
       history.filterByAvailability();
       // populateTable(list);
        
    }//GEN-LAST:event_btnCarAvailabilityActionPerformed

    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
         //DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        String serialNumber1 = null;
        String serialNumber = JOptionPane.showInputDialog("Enter the Serial number you want to search by ", serialNumber1);
        ArrayList<CarDetails> list = history.filterbySerialNumber(serialNumber);
        populateTable(list);
             
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void btnCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarNameActionPerformed
        // TODO add your handling code here:

       ArrayList<CarDetails> list = history.filterbyFirstPassengerCar();
       populateTable(list);
        
    }//GEN-LAST:event_btnCarNameActionPerformed

    private void btnManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturingYearActionPerformed
        // TODO add your handling code here:
        
       String manufacturingYear1 = null;
       String manufacturingYear = JOptionPane.showInputDialog("Enter the car manufacturing year", manufacturingYear1);
       ArrayList<CarDetails> list = history.filterbyManufacturingYear(manufacturingYear);
       populateTable(list); 
        
        
    }//GEN-LAST:event_btnManufacturingYearActionPerformed

    private void btnBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandNameActionPerformed
        // TODO add your handling code here:
        
       String BrandName1 = null;
       String brandName = JOptionPane.showInputDialog(null, "Enter the car brand name you want to search by", BrandName1);
       ArrayList<CarDetails> list = history.filterbyBrandName(brandName);
       populateTable(list); 
       
       //DONE
       
    }//GEN-LAST:event_btnBrandNameActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
         //DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       String seats1 = null;
       String seats = JOptionPane.showInputDialog("Enter the minimum and maximum number of car seats ", seats1);
       ArrayList<CarDetails> list = history.filterBySeatCount(seats);
       populateTable(list); 
        
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNumberActionPerformed
        // TODO add your handling code here:
         //DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
         String modelNumber1 = null;
        String modelNumber = JOptionPane.showInputDialog("Enter the car model number you want to search by ", modelNumber1);
       ArrayList<CarDetails> list = history.filterByModelNum(modelNumber);
        populateTable(list);
        
    }//GEN-LAST:event_btnModelNumberActionPerformed

    private void btnCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityNameActionPerformed
        // TODO add your handling code here:
         //DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
       String cityName1 = null;
       String cityName = JOptionPane.showInputDialog("Enter the City name for available cars you want to search by ", cityName1);
       ArrayList<CarDetails> list = history.filterByCity(cityName);
        populateTable(list);
    }//GEN-LAST:event_btnCityNameActionPerformed

    private void btnExpiredCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredCertificateActionPerformed
        // TODO add your handling code here
       ArrayList<CarDetails> list = history.filterByExpiry();
       populateTable(list);
        
        
    }//GEN-LAST:event_btnExpiredCertificateActionPerformed

    private void btnManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturersActionPerformed
        // TODO add your handling code here:

        populateTable(history.getHistory());
       
        
    }//GEN-LAST:event_btnManufacturersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrandName;
    private javax.swing.JButton btnCarAvailability;
    private javax.swing.JButton btnCarName;
    private javax.swing.JButton btnCityName;
    private javax.swing.JButton btnExpiredCertificate;
    private javax.swing.JButton btnManufacturers;
    private javax.swing.JButton btnManufacturingYear;
    private javax.swing.JButton btnModelNumber;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearchCarDetails;
    private javax.swing.JLabel txtSearchTitle;
    // End of variables declaration//GEN-END:variables

   
private void populateTable(ArrayList<CarDetails> list) {
        DefaultTableModel model = (DefaultTableModel) tblSearchCarDetails.getModel();
        model.setRowCount(0);
       
        for(CarDetails cd: list){
            Object[] row = new Object[9];
            row[0] = cd;
            row[1] = cd.getCarAvailability();
            row[2] = cd.getBrandName();
            row[3] = cd.getManufacturingYear();
            row[4] = cd.getSeats();
            row[5] = cd.getSerialNumber();
            row[6] = cd.getModelNumber();
            row[7] = cd.getCityName();
            row[8] = cd.getExpiredCertificate();
            
            model.addRow(row);
            
        }
        
        
    }
}